Improved grid
Alexandru-Bulai/website-project pull request #19
Opened 2023-12-22 11:21 UTC by Alexandru-Bulai

# PR 22 - 12 - 23 

## Changes

- Add `class: "grid__text"` to modify on each grid box to modify the text more accurately
- Improve grid style with box-size and add hover effect with shadows

![Screenshot 2023-12-22 110606](https://github.com/Alexandru-Bulai/website-project/assets/114404620/dff76a68-6139-40d9-b536-e05b36790326)
dows

2023-12-24 23:43 UTC, vladiiancu requested changes

2023-12-24 23:43 UTC, vladiiancu commented on CSS/home style/home_grid.css
> +    font-family: 'Poppins', 'Arial';
Where is this font defined?

2023-12-25 09:34 UTC, Alexandru-Bulai commented on CSS/home style/home_grid.css
> +    font-family: 'Poppins', 'Arial';
True, that is not changing anything

2023-12-26 01:05 UTC, vladiiancu commented on CSS/home style/home_grid.css
> +    font-family: 'Poppins', 'Arial';
Well then... you either use the poppies font by inserting it ikon your website or you delete this entry

2023-12-26 01:08 UTC, vladiiancu requested changes
Resolve conflicts as well

2023-12-26 16:10 UTC, vladiiancu approved these changes

2023-12-26 16:10 UTC, merged