Development
Alexandru-Bulai/website-project pull request #3
Opened 2023-12-06 09:02 UTC by Alexandru-Bulai

2023-12-06 16:11 UTC, vladiiancu commented
Nice improvements on the commit messages.

2023-12-06 16:12 UTC, vladiiancu commented
A good PR will also have a short summary of the changes, the reasons etc. It is a bit harder for the first few ones but it becomes easier. 
A screenshot with how the page looks like now after all the changes is also a nice addition

2023-12-06 16:28 UTC, Alexandru-Bulai commented
How would you do it? 
Should I create a new folder just for that and in each commit I put the PR there?

2023-12-07 14:07 UTC, Alexandru-Bulai reviewed
PR  7-12-23:

Removed the "p" elements from the grid and replaced them with a "div" instead for better manipulation object.
Added images on each div on the grid that represent  the descipriton.

Changed the background-color of the body for better UI 

Screeshot of the home page with changes applied: 
![screenshot page 7-12](https://github.com/Alexandru-Bulai/website-project/assets/114404620/1dffb78e-4573-4dc5-9e3e-74805ab48909)

2023-12-08 11:20 UTC, vladiiancu requested changes
Please make changes according to the leftover comments or, if no changes made now, acknowledge that you read the comment so that we can continue

2023-12-08 11:20 UTC, vladiiancu commented on how_to.html
I would not include an empty page in a PR.

2023-12-08 11:20 UTC, vladiiancu commented on index.html
While your change from index.html to home.html is fine, you should know this: Most web servers, by default are looking at the root directory for one of the following files: index.html, index.htm, index.php and so on. 

Of course, the settings can be changed without a problem but that's why, probably most of the websites have an index.html as the main file. 

You can keep the change to home.html - no worries. Just some background info for you.

2023-12-08 11:20 UTC, vladiiancu commented on CSS/style.css
> +  font-style: italic;
font-style: italic on a class used on a p element. And that p element, contains a `<strong>` element. So, would it make more sense to have 
`<em><strong>Bold and italic text</strong> and some more italic text</em>`
And have this wrapped inside a `<p>`.

instead of
`<p class="home_title"><strong>Bold and italic text</strong> and some more italic text</p>`   ?

2023-12-08 11:20 UTC, vladiiancu commented on home.html
> +            <p class="home_grid_item"><strong>Peace of Mind</strong></p>
When you reach the CSS lectures, make note of the BEM naming convention https://en.bem.info/methodology/naming-convention/ 
It might come in handy :)

2023-12-08 11:20 UTC, vladiiancu commented on Assets/images/home/gif1-500x.gif
Nice :+1:

2023-12-12 13:12 UTC, vladiiancu approved these changes, later dismissed

2023-12-12 13:12 UTC, vladiiancu commented on home.html
> +        <img src="Assets/images/footer/facebook.png" alt="Facebook icon">
don't you need to have links on each one of them?

2023-12-12 13:12 UTC, vladiiancu commented on home.html
> +        <img src="Assets/images/home/gif1-500x.gif" alt="GIF">
alt text should be more descriptive

2023-12-12 13:12 UTC, Alexandru-Bulai commented
PR 12-12-23  13:00 :

Footer : 
changed structure into a more profesisonal looking footer, added social media imgs and location button

Header : 
changed menu style and hover effect
 
![Screenshot 2023-12-12 130128](https://github.com/Alexandru-Bulai/website-project/assets/114404620/c7ac29f4-a9b8-49e7-9fa4-c0e3cb9e0333)
![Screenshot 2023-12-12 130155](https://github.com/Alexandru-Bulai/website-project/assets/114404620/5a2f9e32-9993-485e-b1e6-f55e6643c35f)

2023-12-12 15:38 UTC, Alexandru-Bulai commented
PR 12-12-23 15:30 :

Footer :

finished design on footer and added links on social media logos.

![Screenshot 2023-12-12 153752](https://github.com/Alexandru-Bulai/website-project/assets/114404620/88a60c94-2662-4a10-99e5-d98965e57f2c)

2023-12-12 15:59 UTC, vladiiancu approved these changes

2023-12-12 16:00 UTC, merged