add dockerignore file
Alexandru-Bulai/website-project pull request #49
Opened 2024-01-16 19:06 UTC by Alexandru-Bulai

#47  # PR 16-01-24
## Overview:
This PR adds a dockerignore file that excludes the unnecessary file related to the website
## Key changes : 
1) Add dockerignore file:
   - Add to the dockerignore file the files that are not needed for the website to run

2024-01-16 19:12 UTC, vladiiancu commented
New rule is that any PR will be merged only if it passes all checks.

2024-01-16 19:13 UTC, vladiiancu requested changes
I am not a big fan of this change. 
While it seems to solve the issue one, what about in the future? When we will add new files and folders in the root project (and not only!) and they will also get copied over. 

What will you do then? Always keep this file in sync? It is prone to error. 

Can you think of another way to solve this issue?

2024-01-16 19:51 UTC, vladiiancu requested changes
Not sure why JS changes are part of this PR though. 
The rest of the comments remain

2024-01-16 19:51 UTC, vladiiancu commented on JavaScript/common.js
> -const nav_button = document.getElementById("nav_button");
Changing the class name is unnecessary

2024-01-16 19:51 UTC, vladiiancu commented on .dockerignore
> +# Whitelist method
ok, but now you just inverted the original issue. 
If you add a CSS file, what now? You still need to update this file to include it in the whitelist, right? 

Find the root cause and fix that.

2024-01-16 20:58 UTC, Alexandru-Bulai commented
> New rule is that any PR will be merged only if it passes all checks.

This is the only reason why i made few changes on JS file.... to pass the lintern so it can be merged when i solve the problem with the dockerignore

2024-01-16 23:28 UTC, vladiiancu requested changes
You are on a better path. 
You moved some files around to better organize.

My recommendation is simpler. Drop the docker ignore file as it is not needed at this point. 

Put all the files required for the website in a folder such as "public" or "web" or similar.

Adjust the docker image to only copy the contents of that folder in the apache server. 

And you are done. Easy and clean

2024-01-17 00:28 UTC, vladiiancu requested changes

2024-01-17 00:28 UTC, vladiiancu commented on README.md
> +3. Run `docker-compose up -d` OR `docker compose up -d`.
Why would I run docker from the public folder? 
Is compose.yaml a file that should be public to an end user?

2024-01-17 00:28 UTC, vladiiancu commented on .gitignore
Why is gitignore removed?

2024-01-17 00:42 UTC, vladiiancu requested changes
I know this has been a lot of back and forth.
But we are on a good path. 

Now let's tidy things up, please. Adjust the PR title and description to match what you actually did :)

2024-01-17 05:47 UTC, vladiiancu approved these changes
I changed the pr title and we are now good to go

2024-01-17 09:52 UTC, merged