Set up Jest enviroment
Alexandru-Bulai/website-project pull request #51
Opened 2024-01-17 18:53 UTC by Alexandru-Bulai

#48 PR 17-01-24 
## Overview
In this PR i added the basic envirooment to run tests with Jest and a folder dedicateed for that named test (that is empty at the time being). 

## Key changes :
1) Jest installation:
   - I runned `npm init -y` to initialize the default value
   - After i installed Jest with `npm i --save-dev jest`
   - Modified the package.json script to run jest `script: {"test" : "test --coverage"`
   - I used `--coverage` to get a better UI on the cmd and also gives us more informations
2) Update README :
   - Modified the readme file with who to setup the testing enviroment as optional
   - Also provided a video in case they need further help 
# Additional note 
## Testing jest :
Below on the screenshot i created and tested a function to see if jest was working as expected (is not included on this PR of course)

<img width="753" alt="Screenshot 2024-01-17 at 17 54 57" src="https://github.com/Alexandru-Bulai/website-project/assets/114404620/7799ac59-f940-4848-acb3-99f902c0fc9e">

2024-01-17 18:59 UTC, vladiiancu commented
I would install https://marketplace.visualstudio.com/items?itemName=standard.vscode-standard to avoid having JS Lint Issues in the future in this Github action

2024-01-17 19:01 UTC, Alexandru-Bulai commented
> I would install https://marketplace.visualstudio.com/items?itemName=standard.vscode-standard to avoid having JS Lint Issues in the future in this Github action

Oh thanks, i didn't know about that :)

2024-01-17 19:09 UTC, vladiiancu requested changes

2024-01-17 19:09 UTC, vladiiancu commented on README.md
> +1. Run `npm init -y` to initialize default value.
Any other developer doesn't need to do this. What does this command do? It creates a package.json file correct? This file is now in git. 
If i run this command I would probably get an error.

2024-01-17 19:09 UTC, vladiiancu commented on README.md
> +2. Install jest with `npm --save-dev jest`.
as above, this dependancy is already writen in package.json file so  I don't need to run this again

2024-01-17 19:09 UTC, vladiiancu commented on package.json
> +  "description": "[![Super-Linter](https://github.com/<OWNER>/<REPOSITORY>/actions/workflows/<WORKFLOW_FILE_NAME>/badge.svg)](https://github.com/marketplace/actions/super-linter)",
this description should be changed

2024-01-18 00:09 UTC, vladiiancu approved these changes

2024-01-18 00:09 UTC, vladiiancu commented on .gitignore
> +node_modules
Good

2024-01-18 00:10 UTC, merged